version: 2.1
# https://circleci.com/docs/2.0/configuration-reference/
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - restore_cache:
          key: yarn-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - checkout
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: yarn-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: yarn release-ci
workflows:
  version: 2
  release:
    jobs:
      - build
