version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache:
        keys:
        # when lock file changes, use increasingly general patterns to restore cache
          - node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - node-v1-{{ .Branch }}-
          - node-v1-
      - save_cache:
        paths:
          - ~/usr/local/lib/node_modules  # location depends on npm version
        key: node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: yarn release-ci
workflows:
  version: 2
  release:
    jobs:
      - build
