version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: yarn
      - run: yarn release-ci
workflows:
  version: 2
  release:
    jobs:
      - build
